### ISSUE TITLE
Unable to download archive

### ISSUE THREAD

**Issue by Palak3196** [ElrondNetwork/db-archive-scripts#3]
Hi Team,

I was trying to download rosetta historical snapshot as suggested by Andrei on Telegram:

I clone the repo and completed the prerequisite. I have exported the URL as provided.

However, as soon as I run command: `python3 ./archive_py/download.py --folder=~/deep-history-archives/mainnet/shard-0 --url=${URL}/mainnet/shard-0 --epochs=605:829 --include-static`

I get this error:
```
palak@server73:/Disk1/node-elrond-rosetta/db-archive-scripts$ python3 ./archive_py/download.py --folder=/ThirdDisk73Machine/node-elrond-rosetta/deep-history-archives/mainnet/shard-0 --url=${URL}/mainnet/shard-0 --epochs=605:829 --include-static
Traceback (most recent call last):
  File "./archive_py/download.py", line 5, in <module>
    from archive_py.args import parse_epochs_arg
ModuleNotFoundError: No module named 'archive_py'
```

**Comment by andreibancioiu** [comment]
Hello @Palak3196,

Don't forget to export the variable `PYTHONPATH`.

```
export PYTHONPATH=.
```

**Comment by schimih** [comment]
Hey @Palak3196 ,
Does the issue still persist?

**Comment by schimih** [comment]
Issue closed due to inactivity from the person raising the issue.
If the problem persists, please open the issue again.
